name: Node.js & Deno CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 12
          cache: 'npm'
      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - run: deno test --allow-read deno-test/*.ts
